In [ ]:
import numpy as np

In [4]:
np.__version__

'1.25.2'

#

In [6]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [7]:
b = np.array([[5, 6], [7, 8]])
a+b


array([[ 6,  8],
       [10, 12]])

In [9]:
import numpy as np

# Example 1D ndarray of theta (angles in degrees)
theta = np.array([30, 45, 60])  # Shape: (3,)

# Convert theta to radians
theta_rad = np.radians(theta)  # Shape: (3,)

# Calculate cosine and sine for each angle
cos_theta = np.cos(theta_rad)  # Shape: (3,)
sin_theta = np.sin(theta_rad)  # Shape: (3,)

# Stack components to construct the rotation matrices
rotation_matrices = np.array([
    [cos_theta, -sin_theta],
    [sin_theta,  cos_theta]
])
rotation_matrices

array([[[ 0.8660254 ,  0.70710678,  0.5       ],
        [-0.5       , -0.70710678, -0.8660254 ]],

       [[ 0.5       ,  0.70710678,  0.8660254 ],
        [ 0.8660254 ,  0.70710678,  0.5       ]]])

In [10]:

# Transpose axes to create a (3, 2, 2) array
rotation_matrices = np.transpose(rotation_matrices, (2, 0, 1))

print("Rotation matrices shape:", rotation_matrices.shape)
print(rotation_matrices)


Rotation matrices shape: (3, 2, 2)
[[[ 0.8660254  -0.5       ]
  [ 0.5         0.8660254 ]]

 [[ 0.70710678 -0.70710678]
  [ 0.70710678  0.70710678]]

 [[ 0.5        -0.8660254 ]
  [ 0.8660254   0.5       ]]]


In [13]:
0.70710678 ** 2 + (-0.70710678) ** 2

0.9999999966439369