In [2]:
import numpy as np

# version

In [4]:
np.__version__

'1.25.2'

# basic construction

In [6]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

# basic operations

In [7]:
b = np.array([[5, 6], [7, 8]])
a+b


array([[ 6,  8],
       [10, 12]])

# basic statistics

In [6]:
np.random.randint(1,10,10)

array([6, 8, 7, 8, 9, 5, 1, 9, 9, 8])