# 坐标转换

In [18]:
import numpy as np
from spacepy import coordinates as coord
from spacepy.time import Ticktock

# 设置时间
t = Ticktock('2023-01-01T12:00:00', 'ISO')  # 'ISO'表示该时间字符串遵循ISO 8601标准，这是一种国际通用的日期和时间表示方法。

# 输入地理坐标
alt = 110   # 高度（km）
lat = 45.0  # degree
lon = 0.0   # degree

c = coord.Coords([alt, lat, lon], 'GDZ', 'sph')
c.ticks = t

# 转换为GSM坐标
c_gsm = c.convert('GSM', 'car')

In [19]:
x0gsm,y0gsm,z0gsm = c_gsm.x[0],c_gsm.y[0],c_gsm.z[0]

In [5]:
# trace
from geopack import geopack

In [6]:
import datetime
# from dateutil import parser

# From date and time
t1 = datetime.datetime(2001,1,2,3,4,5)
t0 = datetime.datetime(1970,1,1)
ut = (t1-t0).total_seconds()

# From string, need the package dateutil
# t1 = parser.parse('2001-01-02/03:04:05')
# ut = (t1-t0).total_seconds()

In [20]:
ps = geopack.recalc(ut)

In [21]:
x1gsm,y1gsm,z1gsm,xx,yy,zz = geopack.trace(x0gsm,y0gsm,z0gsm, dir=1)

In [22]:
c = coord.Coords([x1gsm,y1gsm,z1gsm], 'GSM', 'car')

In [23]:
c.ticks = t

In [24]:
c_gdz = c.convert('GDZ','sph')

In [25]:
alt,lat,lon

(110, 45.0, 0.0)

In [26]:
c_gdz.data

array([[ -3.11244238, -24.06631305,  14.24660168]])

In [32]:
import numpy as np

# 设置时间
t = Ticktock(np.array(['2023-01-01T12:00:00','2023-01-01T12:00:00','2023-01-01T12:00:00']), 'ISO')  # 'ISO'表示该时间字符串遵循ISO 8601标准，这是一种国际通用的日期和时间表示方法。

# 输入地理坐标
alt = 110   # 高度（km）
lat = 45.0  # degree
lon = 0.0   # degree

c = coord.Coords([np.array([110,400,800]), [50,50,50], [0,0,0]], 'GDZ', 'sph')
c.ticks = t

In [33]:
c.data

array([[110., 400., 800.],
       [ 50.,  50.,  50.],
       [  0.,   0.,   0.]])

In [34]:
c_gsm = c.convert('GSM', 'car')


In [35]:
c_gsm.data

array([[-0.26000735,  0.5698426 ,  0.89449202],
       [ 0.7144055 ,  0.52848679,  0.21932455],
       [ 0.60966242,  0.79045265,  0.13060764]])

In [ ]:
ps = geopack.recalc(ut)


Spacepy version: 0.7.0


TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'int'